[features]
seeds = false
skip-lint = false

[programs.devnet]
smartcontract = "HPHXtE7dhKP8R1iANQeTZiSFpYcpzmqjBz1CTTunfj4K"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/kali/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
